
spring:
    datasource:
        platform: h2
        url: jdbc:h2:file:~/.h2/demo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
        username: sa        
        driver-class-name: org.h2.Driver
    flyway:
        default-schema: FLYWAY        
        schemas: 
        - FLYWAY