DROP TABLE IF EXISTS DEMO_TABLE;
CREATE TABLE DEMO_TABLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

INSERT INTO DEMO_TABLE(NAME) VALUES('NOMBRE 1');
INSERT INTO DEMO_TABLE(NAME) VALUES('NOMBRE 2');
INSERT INTO DEMO_TABLE(NAME) VALUES('NOMBRE 3');
INSERT INTO DEMO_TABLE(NAME) VALUES('NOMBRE 4');
INSERT INTO DEMO_TABLE(NAME) VALUES('NOMBRE 5');